=== webuild-consortium/wp4-trust-group/tools/lotl/schemas/tl_entry.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TL Entry",
  "description": "Trusted List entry for LoTL - one file per participant per TL type",
  "type": "object",
  "required": ["tl_url", "trust_anchor"],
  "properties": {
    "tl_url": {
      "type": "string",
      "format": "uri",
      "description": "URL of the TL (JSON or XML; at least one format)"
    },
    "tl_url_xml": {
      "type": "string",
      "format": "uri",
      "description": "URL of the TL in XML format (if different from tl_url)"
    },
    "tl_url_json": {
      "type": "string",
      "format": "uri",
      "description": "URL of the TL in JSON format (if different from tl_url)"
    },
    "trust_anchor": {
      "type": "string",
      "description": "X.509 certificate in PEM format - used to validate the TL signature"
    },
    "metadata": {
      "type": "object",
      "description": "Additional metadata per TL type (e.g. operator name, country)",
      "additionalProperties": true
    }
  },
  "additionalProperties": false
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/pub-eaa-provider/nxd-foundation.json
{
  "tl_url": "https://trustlist.nxd.foundation/trust-lists/nxd-pub-eaa-providers-lote.json",
  "tl_url_xml": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-PubEAA.xml",
  "tl_url_json": "https://trustlist.nxd.foundation/trust-lists/nxd-pub-eaa-providers-lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIIBnzCCAUagAwIBAgIUTtUzk8xi3gSAgdmjOB3Ngvj72bQwCgYIKoZIzj0EAwIw\nJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoMDk5YRCBGb3VuZGF0aW9uMB4XDTI2MDcw\nOTEwMjM0NloXDTI5MDcwODEwMjM0NlowJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoM\nDk5YRCBGb3VuZGF0aW9uMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQVTqk6oG\nWN4G15IcOeW27Pp4Akfu54kGaoT1JNNAJbnB7v3zZu1o/9/gHoyrN6Yyu9ww0dAU\nxsWPQFcq2/+U56NSMFAwDgYDVR0PAQH/BAQDAgbAMBEGA1UdJQQKMAgGBgQAkTcD\nADAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVww37whbwN3DMilF8pSAtQRgIsTAK\nBggqhkjOPQQDAgNHADBEAiA+ISJxsJUvpgYGwAwGo9lBW5e4Z8xxuiFxD4okDlVA\n5gIgUUn3SoF11O2xO8/G9xRHRGENgDQutBst2x26txx0VEI=\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "NXD Foundation",
    "country": "SE"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/wallet-provider/nxd-foundation.json
{
  "tl_url": "https://trustlist.nxd.foundation/trust-lists/nxd-wallet-providers-lote.json",
  "tl_url_xml": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-WalletProviders.xml",
  "tl_url_json": "https://trustlist.nxd.foundation/trust-lists/nxd-wallet-providers-lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIIBnzCCAUagAwIBAgIUTtUzk8xi3gSAgdmjOB3Ngvj72bQwCgYIKoZIzj0EAwIw\nJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoMDk5YRCBGb3VuZGF0aW9uMB4XDTI2MDcw\nOTEwMjM0NloXDTI5MDcwODEwMjM0NlowJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoM\nDk5YRCBGb3VuZGF0aW9uMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQVTqk6oG\nWN4G15IcOeW27Pp4Akfu54kGaoT1JNNAJbnB7v3zZu1o/9/gHoyrN6Yyu9ww0dAU\nxsWPQFcq2/+U56NSMFAwDgYDVR0PAQH/BAQDAgbAMBEGA1UdJQQKMAgGBgQAkTcD\nADAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVww37whbwN3DMilF8pSAtQRgIsTAK\nBggqhkjOPQQDAgNHADBEAiA+ISJxsJUvpgYGwAwGo9lBW5e4Z8xxuiFxD4okDlVA\n5gIgUUn3SoF11O2xO8/G9xRHRGENgDQutBst2x26txx0VEI=\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "NXD Foundation",
    "country": "SE"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/wrprc-provider/credimi.json
{
  "tl_url": "https://lote.credimi.io/lists/eu_credimi_wrprc_trust_registry_infrastruct/latest/lote.jades",
  "tl_url_json": "https://lote.credimi.io/lists/eu_credimi_wrprc_trust_registry_infrastruct/latest/lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIICfjCCAiSgAwIBAgIUd+nAY0mKz1FSJYIhDwOibv7wtX4wCgYIKoZIzj0EAwIw\ngY0xCzAJBgNVBAYTAkVVMTQwMgYDVQQKDCtDcmVkaW1pIFdSUFJDIFRydXN0IFJl\nZ2lzdHJ5IEluZnJhc3RydWN0dXJlMUgwRgYDVQQDDD9DcmVkaW1pIFdSUFJDIFRy\ndXN0IFJlZ2lzdHJ5IEluZnJhc3RydWN0dXJlIFRydXN0ZWQgTGlzdCBTaWduZXIw\nHhcNMjYwODA0MTMyNTUwWhcNMjcwODA0MTMyNTUwWjCBjTELMAkGA1UEBhMCRVUx\nNDAyBgNVBAoMK0NyZWRpbWkgV1JQUkMgVHJ1c3QgUmVnaXN0cnkgSW5mcmFzdHJ1\nY3R1cmUxSDBGBgNVBAMMP0NyZWRpbWkgV1JQUkMgVHJ1c3QgUmVnaXN0cnkgSW5m\ncmFzdHJ1Y3R1cmUgVHJ1c3RlZCBMaXN0IFNpZ25lcjBZMBMGByqGSM49AgEGCCqG\nSM49AwEHA0IABPLvp1BCDp781mlJK8GOfJzpZ7nr6HX1o8po4YyRU5I2IInYPauU\n4PIXeYvs7Qu9kZzsTfkclf5jBVzTd9vzqmqjYDBeMB8GA1UdIwQYMBaAFDGy/aKP\n386tbc4+WWmGoRoS7kikMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMB0G\nA1UdDgQWBBQxsv2ij9/OrW3OPllphqEaEu5IpDAKBggqhkjOPQQDAgNIADBFAiBJ\nWbdJx0j6iW/Nk5wyugRKKM34BnyXVyHnQkOHggBO2gIhAMIdlx7XhJVni74xveck\nOjuTiIOpU8l02LSS4rxtTeEp\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "Credimi WRPRC Trust Registry Infrastructure",
    "country": "EU"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/qeaa-provider/nxd-foundation.json
{
  "tl_url": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-QEAA.xml",
  "tl_url_xml": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-QEAA.xml",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIIBoDCCAUagAwIBAgIUeQPc75dyOVwCJVf0X5gtsJ8tkbMwCgYIKoZIzj0EAwIw\nJjELMAkGA1UEBhMCU0UxFzAVBgNVBAoMDk5YRCBGb3VuZGF0aW9uMB4XDTI2MDky\nMTA5NDgzOVoXDTI5MDkyMDA5NTMzOVowJjELMAkGA1UEBhMCU0UxFzAVBgNVBAoM\nDk5YRCBGb3VuZGF0aW9uMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQVTqk6oG\nWN4G15IcOeW27Pp4Akfu54kGaoT1JNNAJbnB7v3zZu1o/9/gHoyrN6Yyu9ww0dAU\nxsWPQFcq2/+U56NSMFAwDgYDVR0PAQH/BAQDAgbAMBEGA1UdJQQKMAgGBgQAkTcD\nADAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVww37whbwN3DMilF8pSAtQRgIsTAK\nBggqhkjOPQQDAgNIADBFAiBR4C7Tiv94JRayfJ19gggyj68PjdfOfHuCe0Y6B9Gg\nJgIhAKIw81dJK5lGBZXM2d3FSfKAmYH1TpK3TEAjxeZenO4S\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "NXD Foundation",
    "country": "SE"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/ebwoid-provider/nxd-foundation.json
{
  "tl_url": "https://trustlist.nxd.foundation/trust-lists/nxd-registrars-and-registers-lote.json",
  "tl_url_xml": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-Registrars.xml",
  "tl_url_json": "https://trustlist.nxd.foundation/trust-lists/nxd-registrars-and-registers-lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIIBnzCCAUagAwIBAgIUTtUzk8xi3gSAgdmjOB3Ngvj72bQwCgYIKoZIzj0EAwIw\nJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoMDk5YRCBGb3VuZGF0aW9uMB4XDTI2MDcw\nOTEwMjM0NloXDTI5MDcwODEwMjM0NlowJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoM\nDk5YRCBGb3VuZGF0aW9uMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQVTqk6oG\nWN4G15IcOeW27Pp4Akfu54kGaoT1JNNAJbnB7v3zZu1o/9/gHoyrN6Yyu9ww0dAU\nxsWPQFcq2/+U56NSMFAwDgYDVR0PAQH/BAQDAgbAMBEGA1UdJQQKMAgGBgQAkTcD\nADAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVww37whbwN3DMilF8pSAtQRgIsTAK\nBggqhkjOPQQDAgNHADBEAiA+ISJxsJUvpgYGwAwGo9lBW5e4Z8xxuiFxD4okDlVA\n5gIgUUn3SoF11O2xO8/G9xRHRGENgDQutBst2x26txx0VEI=\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "NXD Foundation",
    "country": "SE"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/pub-eaa-provider/credimi.json
{
  "tl_url": "https://lote.credimi.io/lists/eu_credimi_pub-eaa_trust_registry_infrastru/latest/lote.jades",
  "tl_url_json": "https://lote.credimi.io/lists/eu_credimi_pub-eaa_trust_registry_infrastru/latest/lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIICgzCCAiqgAwIBAgIUJCKENiyiTwHmign0BOWjrUX/+E8wCgYIKoZIzj0EAwIw\ngZAxCzAJBgNVBAYTAkVVMTYwNAYDVQQKDC1DcmVkaW1pIFB1Yi1FQUEgVHJ1c3Qg\nUmVnaXN0cnkgSW5mcmFzdHJ1Y3R1cmUxSTBHBgNVBAMMQENyZWRpbWkgUHViLUVB\nQSBUcnVzdCBSZWdpc3RyeSBJbmZyYXN0cnVjdHVyZSBUcnVzdGVkIExpc3QgU2ln\nbmUwHhcNMjYwODA0MTMyODQzWhcNMjcwODA0MTMyODQzWjCBkDELMAkGA1UEBhMC\nRVUxNjA0BgNVBAoMLUNyZWRpbWkgUHViLUVBQSBUcnVzdCBSZWdpc3RyeSBJbmZy\nYXN0cnVjdHVyZTFJMEcGA1UEAwxAQ3JlZGltaSBQdWItRUFBIFRydXN0IFJlZ2lz\ndHJ5IEluZnJhc3RydWN0dXJlIFRydXN0ZWQgTGlzdCBTaWduZTBZMBMGByqGSM49\nAgEGCCqGSM49AwEHA0IABABrI/4lOf1oR4gbhPJXv3764xShHd0vFxyO3wGpQZKn\n+qgxxGmFaYL+Abd4KG3RewPvJOs+NiStGlyx49kMNC2jYDBeMB8GA1UdIwQYMBaA\nFCtE6+kyq9aqKEbusGLjDQYbIQwFMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQD\nAgeAMB0GA1UdDgQWBBQrROvpMqvWqihG7rBi4w0GGyEMBTAKBggqhkjOPQQDAgNH\nADBEAiAVILY1/GDyMFw1QiYtiVGA2LPcTSpLkXS+w3MXsm+DUgIgLEltLGWx22JJ\nIe4vxmStEgGu7LKOxpWNZ9pmhVHva6o=\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "Credimi Pub-EAA Trust Registry Infrastructure",
    "country": "EU"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/wrpac-provider/credimi.json
{
  "tl_url": "https://lote.credimi.io/lists/eu_credimi_wrpac_trust_registry_infrastruct/latest/lote.jades",
  "tl_url_json": "https://lote.credimi.io/lists/eu_credimi_wrpac_trust_registry_infrastruct/latest/lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIICfTCCAiSgAwIBAgIUM2795qKczc8jTWWry8i/xOxF1qEwCgYIKoZIzj0EAwIw\ngY0xCzAJBgNVBAYTAkVVMTQwMgYDVQQKDCtDcmVkaW1pIFdSUEFDIFRydXN0IFJl\nZ2lzdHJ5IEluZnJhc3RydWN0dXJlMUgwRgYDVQQDDD9DcmVkaW1pIFdSUEFDIFRy\ndXN0IFJlZ2lzdHJ5IEluZnJhc3RydWN0dXJlIFRydXN0ZWQgTGlzdCBTaWduZXIw\nHhcNMjYwODA0MTMyMjI1WhcNMjcwODA0MTMyMjI1WjCBjTELMAkGA1UEBhMCRVUx\nNDAyBgNVBAoMK0NyZWRpbWkgV1JQQUMgVHJ1c3QgUmVnaXN0cnkgSW5mcmFzdHJ1\nY3R1cmUxSDBGBgNVBAMMP0NyZWRpbWkgV1JQQUMgVHJ1c3QgUmVnaXN0cnkgSW5m\ncmFzdHJ1Y3R1cmUgVHJ1c3RlZCBMaXN0IFNpZ25lcjBZMBMGByqGSM49AgEGCCqG\nSM49AwEHA0IABJmg2iEDUo34qLTSG91aANAAjHhIQDEwGBYZQQ9YIQYYcJP/Rf8Y\nElM/jD3GqW+VBsTcV3DbTuuO1CiSsACCdLujYDBeMB8GA1UdIwQYMBaAFC/O0sXY\n2JLkof983FdkiiiMF6f2MAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMB0G\nA1UdDgQWBBQvztLF2NiS5KH/fNxXZIoojBen9jAKBggqhkjOPQQDAgNHADBEAiBM\nL2LU6bKkqSoU8TtWfO0eysUIEhHxpv64kdncxzp+igIgGD0OAN9bZ53lBk4F9AMZ\nzpa4JFHiKafxpEbmjsSJUH0=\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "Credimi WRPAC Trust Registry Infrastructure",
    "country": "EU"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/wallet-provider/credimi.json
{
  "tl_url": "https://lote.credimi.io/lists/eu_credimi_wallet_trust_registry_infrastruc/latest/lote.jades",
  "tl_url_json": "https://lote.credimi.io/lists/eu_credimi_wallet_trust_registry_infrastruc/latest/lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIICgjCCAiigAwIBAgIUFF107a1pQGSiR9AJck/5vY9o1FcwCgYIKoZIzj0EAwIw\ngY8xCzAJBgNVBAYTAkVVMTUwMwYDVQQKDCxDcmVkaW1pIFdhbGxldCBUcnVzdCBS\nZWdpc3RyeSBJbmZyYXN0cnVjdHVyZTFJMEcGA1UEAwxAQ3JlZGltaSBXYWxsZXQg\nVHJ1c3QgUmVnaXN0cnkgSW5mcmFzdHJ1Y3R1cmUgVHJ1c3RlZCBMaXN0IFNpZ25l\ncjAeFw0yNjA4MDQxMzE5MjBaFw0yNzA4MDQxMzE5MjBaMIGPMQswCQYDVQQGEwJF\nVTE1MDMGA1UECgwsQ3JlZGltaSBXYWxsZXQgVHJ1c3QgUmVnaXN0cnkgSW5mcmFz\ndHJ1Y3R1cmUxSTBHBgNVBAMMQENyZWRpbWkgV2FsbGV0IFRydXN0IFJlZ2lzdHJ5\nIEluZnJhc3RydWN0dXJlIFRydXN0ZWQgTGlzdCBTaWduZXIwWTATBgcqhkjOPQIB\nBggqhkjOPQMBBwNCAAS0SEvENvGzAZCBPxEJl1JUyUKiaTLSvqOzwUh3wsqn4QaG\nbcpKLgm3dlQQ5yrz6Ucx6/JC9jZPYaK0YYryYcmxo2AwXjAfBgNVHSMEGDAWgBSa\nO5PZByTwUTmX9GrH+8nTuSTujDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIH\ngDAdBgNVHQ4EFgQUmjuT2Qck8FE5l/Rqx/vJ07kk7owwCgYIKoZIzj0EAwIDSAAw\nRQIgMSfhr8YuOe/yO6DId7GvjWD5slc4yTrCap58yaoSuZoCIQCpYGejheCam5Ae\nTiIesaMFILSgOXRZ+R2fB536if5SaA==\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "Credimi Wallet Trust Registry Infrastructure",
    "country": "EU"
  }
}
