=== webuild-consortium/wp4-trust-group/tools/lotl/schemas/tl_entry.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TL Entry",
  "description": "Trusted List entry for LoTL - one file per participant per TL type",
  "type": "object",
  "required": ["tl_url", "trust_anchor"],
  "properties": {
    "tl_url": {
      "type": "string",
      "format": "uri",
      "description": "URL of the TL (JSON or XML; at least one format)"
    },
    "tl_url_xml": {
      "type": "string",
      "format": "uri",
      "description": "URL of the TL in XML format (if different from tl_url)"
    },
    "tl_url_json": {
      "type": "string",
      "format": "uri",
      "description": "URL of the TL in JSON format (if different from tl_url)"
    },
    "trust_anchor": {
      "type": "string",
      "description": "X.509 certificate in PEM format - used to validate the TL signature"
    },
    "metadata": {
      "type": "object",
      "description": "Additional metadata per TL type (e.g. operator name, country)",
      "additionalProperties": true
    }
  },
  "additionalProperties": false
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/qeaa-provider/credimi.json
{
  "tl_url": "https://lote.credimi.io/lists/it_credimi_qeaa_trust_registry_infrastructu/latest/trusted-list.xml",
  "tl_url_xml": "https://lote.credimi.io/lists/it_credimi_qeaa_trust_registry_infrastructu/latest/trusted-list.xml",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIICkDCCAjagAwIBAgIUKY5Ypn2tibtBnbyWpyXX2liR7QAwCgYIKoZIzj0EAwIw\ngYsxCzAJBgNVBAYTAklUMTMwMQYDVQQKDCpDcmVkaW1pIFFFQUEgVHJ1c3QgUmVn\naXN0cnkgSW5mcmFzdHJ1Y3R1cmUxRzBFBgNVBAMMPkNyZWRpbWkgUUVBQSBUcnVz\ndCBSZWdpc3RyeSBJbmZyYXN0cnVjdHVyZSBUcnVzdGVkIExpc3QgU2lnbmVyMB4X\nDTI2MDgwNTEwMzEzN1oXDTI3MDgwNTEwMzEzN1owgYsxCzAJBgNVBAYTAklUMTMw\nMQYDVQQKDCpDcmVkaW1pIFFFQUEgVHJ1c3QgUmVnaXN0cnkgSW5mcmFzdHJ1Y3R1\ncmUxRzBFBgNVBAMMPkNyZWRpbWkgUUVBQSBUcnVzdCBSZWdpc3RyeSBJbmZyYXN0\ncnVjdHVyZSBUcnVzdGVkIExpc3QgU2lnbmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0D\nAQcDQgAE3sT7htkTq+Tzq1LFc95vXcaxUQhiSKE0c6oL1qZI5La8duPZWPpuOX+K\nuG1k1PezXxEA9IBQu3iA4WG/9HIxj6N2MHQwHwYDVR0jBBgwFoAU7/o+v+zFVJcj\nEDEHQALfv/q+1MMwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0O\nBBYEFO/6Pr/sxVSXIxAxB0AC37/6vtTDMBQGA1UdJQEB/wQKMAgGBgQAkTcDADAK\nBggqhkjOPQQDAgNIADBFAiAfipQO7pkbiyALAnCElxK5aKFHxGspUik9O5Sve8ce\nJgIhAPQ6d5+2fXDdUw120AKDy+YGQb8PNYwn8HmGC3838NoN\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "Credimi QEAA Trust Registry Infrastructure",
    "country": "IT"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/pid-provider/credimi.json
{
  "tl_url": "https://lote.credimi.io/lists/eu_credimi_pid_trust_registry_infrastructur/latest/lote.jades",
  "tl_url_json": "https://lote.credimi.io/lists/eu_credimi_pid_trust_registry_infrastructur/latest/lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIICdjCCAhygAwIBAgIUD18jIeuM////itEzYgyGKUU5zmQwCgYIKoZIzj0EAwIw\ngYkxCzAJBgNVBAYTAkVVMTIwMAYDVQQKDClDcmVkaW1pIFBJRCBUcnVzdCBSZWdp\nc3RyeSBJbmZyYXN0cnVjdHVyZTFGMEQGA1UEAww9Q3JlZGltaSBQSUQgVHJ1c3Qg\nUmVnaXN0cnkgSW5mcmFzdHJ1Y3R1cmUgVHJ1c3RlZCBMaXN0IFNpZ25lcjAeFw0y\nNjA4MDMwOTQ3MTdaFw0yNzA4MDMwOTQ3MTdaMIGJMQswCQYDVQQGEwJFVTEyMDAG\nA1UECgwpQ3JlZGltaSBQSUQgVHJ1c3QgUmVnaXN0cnkgSW5mcmFzdHJ1Y3R1cmUx\nRjBEBgNVBAMMPUNyZWRpbWkgUElEIFRydXN0IFJlZ2lzdHJ5IEluZnJhc3RydWN0\ndXJlIFRydXN0ZWQgTGlzdCBTaWduZXIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\nAAQLjUTu4WW0pbcIK9Ve4O8uWHaONCJ/9UC5Cbee70esNJXHeJuPnrvyirCmsIfq\nMpGj/4fARmvq+BMoa+OQJ7bRo2AwXjAfBgNVHSMEGDAWgBTF/QxSqPeNBcXBLzuA\nPJa96JOIwDAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4EFgQU\nxf0MUqj3jQXFwS87gDyWveiTiMAwCgYIKoZIzj0EAwIDSAAwRQIhAJjJU7vrd629\nVYQxLSSEhbIjR8EiR/g2OuAjXgvSnx07AiBI1ErRfPcL1j9LLk0tWv7pYRg4UfqX\nJQum30AjcKc6dg==\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "Credimi PID Trust Registry Infrastructure",
    "country": "EU"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/wrprc-provider/nxd-foundation.json
{
  "tl_url": "https://trustlist.nxd.foundation/trust-lists/nxd-wrprc-providers-lote.json",
  "tl_url_xml": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-WRPRC.xml",
  "tl_url_json": "https://trustlist.nxd.foundation/trust-lists/nxd-wrprc-providers-lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIIBnzCCAUagAwIBAgIUTtUzk8xi3gSAgdmjOB3Ngvj72bQwCgYIKoZIzj0EAwIw\nJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoMDk5YRCBGb3VuZGF0aW9uMB4XDTI2MDcw\nOTEwMjM0NloXDTI5MDcwODEwMjM0NlowJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoM\nDk5YRCBGb3VuZGF0aW9uMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQVTqk6oG\nWN4G15IcOeW27Pp4Akfu54kGaoT1JNNAJbnB7v3zZu1o/9/gHoyrN6Yyu9ww0dAU\nxsWPQFcq2/+U56NSMFAwDgYDVR0PAQH/BAQDAgbAMBEGA1UdJQQKMAgGBgQAkTcD\nADAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVww37whbwN3DMilF8pSAtQRgIsTAK\nBggqhkjOPQQDAgNHADBEAiA+ISJxsJUvpgYGwAwGo9lBW5e4Z8xxuiFxD4okDlVA\n5gIgUUn3SoF11O2xO8/G9xRHRGENgDQutBst2x26txx0VEI=\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "NXD Foundation",
    "country": "SE"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/pid-provider/nxd-foundation.json
{
  "tl_url": "https://trustlist.nxd.foundation/trust-lists/nxd-pid-providers-lote.json",
  "tl_url_xml": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-PID.xml",
  "tl_url_json": "https://trustlist.nxd.foundation/trust-lists/nxd-pid-providers-lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIIBnzCCAUagAwIBAgIUTtUzk8xi3gSAgdmjOB3Ngvj72bQwCgYIKoZIzj0EAwIw\nJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoMDk5YRCBGb3VuZGF0aW9uMB4XDTI2MDcw\nOTEwMjM0NloXDTI5MDcwODEwMjM0NlowJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoM\nDk5YRCBGb3VuZGF0aW9uMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQVTqk6oG\nWN4G15IcOeW27Pp4Akfu54kGaoT1JNNAJbnB7v3zZu1o/9/gHoyrN6Yyu9ww0dAU\nxsWPQFcq2/+U56NSMFAwDgYDVR0PAQH/BAQDAgbAMBEGA1UdJQQKMAgGBgQAkTcD\nADAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVww37whbwN3DMilF8pSAtQRgIsTAK\nBggqhkjOPQQDAgNHADBEAiA+ISJxsJUvpgYGwAwGo9lBW5e4Z8xxuiFxD4okDlVA\n5gIgUUn3SoF11O2xO8/G9xRHRGENgDQutBst2x26txx0VEI=\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "NXD Foundation",
    "country": "SE"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/eaa-provider/credimi.json
{
  "tl_url": "https://lote.credimi.io/lists/it_credimi_eaa_trust_registry_infrastructur/latest/trusted-list.xml",
  "tl_url_xml": "https://lote.credimi.io/lists/it_credimi_eaa_trust_registry_infrastructur/latest/trusted-list.xml",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIICizCCAjKgAwIBAgIUYX8uoJlLFS1DPdxy5gDd9rLy9Y4wCgYIKoZIzj0EAwIw\ngYkxCzAJBgNVBAYTAklUMTIwMAYDVQQKDClDcmVkaW1pIEVBQSBUcnVzdCBSZWdp\nc3RyeSBJbmZyYXN0cnVjdHVyZTFGMEQGA1UEAww9Q3JlZGltaSBFQUEgVHJ1c3Qg\nUmVnaXN0cnkgSW5mcmFzdHJ1Y3R1cmUgVHJ1c3RlZCBMaXN0IFNpZ25lcjAeFw0y\nNjA4MDUxMDI5MTJaFw0yNzA4MDUxMDI5MTJaMIGJMQswCQYDVQQGEwJJVDEyMDAG\nA1UECgwpQ3JlZGltaSBFQUEgVHJ1c3QgUmVnaXN0cnkgSW5mcmFzdHJ1Y3R1cmUx\nRjBEBgNVBAMMPUNyZWRpbWkgRUFBIFRydXN0IFJlZ2lzdHJ5IEluZnJhc3RydWN0\ndXJlIFRydXN0ZWQgTGlzdCBTaWduZXIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC\nAARi5q1Y2ee8P99l30yjeEzdI84VguVPpitLMLUvOu8BOHGMDcI8Mu5IOAAZAxYh\nQJoO8TNTx1MKLiu0nq9Rb9ado3YwdDAfBgNVHSMEGDAWgBRpPWIS6vZ48udHqBOM\nkFp3tra/2jAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDAdBgNVHQ4EFgQU\naT1iEur2ePLnR6gTjJBad7a2v9owFAYDVR0lAQH/BAowCAYGBACRNwMAMAoGCCqG\nSM49BAMCA0cAMEQCIB7Fkfu9TJbDbafBWNTdJ4cjHyB7Z2jWNi4JIOOuA8vVAiAS\n8jQRvLxcodHfY/R45t9mRa8qLsd1D4VoakzCpjZypQ==\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "Credimi EAA Trust Registry Infrastructure",
    "country": "IT"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/eaa-provider/nxd-foundation.json
{
  "tl_url": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-EAA.xml",
  "tl_url_xml": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-EAA.xml",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIIBnzCCAUagAwIBAgIUTtUzk8xi3gSAgdmjOB3Ngvj72bQwCgYIKoZIzj0EAwIw\nJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoMDk5YRCBGb3VuZGF0aW9uMB4XDTI2MDcw\nOTEwMjM0NloXDTI5MDcwODEwMjM0NlowJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoM\nDk5YRCBGb3VuZGF0aW9uMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQVTqk6oG\nWN4G15IcOeW27Pp4Akfu54kGaoT1JNNAJbnB7v3zZu1o/9/gHoyrN6Yyu9ww0dAU\nxsWPQFcq2/+U56NSMFAwDgYDVR0PAQH/BAQDAgbAMBEGA1UdJQQKMAgGBgQAkTcD\nADAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVww37whbwN3DMilF8pSAtQRgIsTAK\nBggqhkjOPQQDAgNHADBEAiA+ISJxsJUvpgYGwAwGo9lBW5e4Z8xxuiFxD4okDlVA\n5gIgUUn3SoF11O2xO8/G9xRHRGENgDQutBst2x26txx0VEI=\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "NXD Foundation",
    "country": "SE"
  }
}

=== webuild-consortium/wp4-trust-group/lotl/tl_entries/wrpac-provider/nxd-foundation.json
{
  "tl_url": "https://trustlist.nxd.foundation/trust-lists/nxd-wrpac-providers-lote.json",
  "tl_url_xml": "https://trustlist.nxd.foundation/trust-lists/NXD-TL-WRPAC.xml",
  "tl_url_json": "https://trustlist.nxd.foundation/trust-lists/nxd-wrpac-providers-lote.json",
  "trust_anchor": "-----BEGIN CERTIFICATE-----\nMIIBnzCCAUagAwIBAgIUTtUzk8xi3gSAgdmjOB3Ngvj72bQwCgYIKoZIzj0EAwIw\nJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoMDk5YRCBGb3VuZGF0aW9uMB4XDTI2MDcw\nOTEwMjM0NloXDTI5MDcwODEwMjM0NlowJjELMAkGA1UEBhMCVFQxFzAVBgNVBAoM\nDk5YRCBGb3VuZGF0aW9uMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQVTqk6oG\nWN4G15IcOeW27Pp4Akfu54kGaoT1JNNAJbnB7v3zZu1o/9/gHoyrN6Yyu9ww0dAU\nxsWPQFcq2/+U56NSMFAwDgYDVR0PAQH/BAQDAgbAMBEGA1UdJQQKMAgGBgQAkTcD\nADAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQVww37whbwN3DMilF8pSAtQRgIsTAK\nBggqhkjOPQQDAgNHADBEAiA+ISJxsJUvpgYGwAwGo9lBW5e4Z8xxuiFxD4okDlVA\n5gIgUUn3SoF11O2xO8/G9xRHRGENgDQutBst2x26txx0VEI=\n-----END CERTIFICATE-----\n",
  "metadata": {
    "operator_name": "NXD Foundation",
    "country": "SE"
  }
}
